.TH "ADB_mod.h" 3 "Сб 16 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADB_mod.h \- Заголовочный файл с подключением модуля работы с adb\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBadb\fP (LPSTR cmdArgs)"
.br
.ti -1c
.RI "int \fBfastboot\fP (LPSTR cmdArgs)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля работы с adb\&. 


.PP
\fBАвтор:\fP
.RS 4
Darlakon 
.RE
.PP

.PP
См\&. определение в файле \fBADB_mod\&.h\fP
.SH "Функции"
.PP 
.SS "int adb (LPSTR cmdArgs)"
Вызов adb-интерфейса\&. LPSTR cmdArgs - команда для adb вида 'adb X'\&. 
.PP
См\&. определение в файле ADB_mod\&.cpp строка 11
.SS "int fastboot (LPSTR cmdArgs)"
Вызов fastboot-интерфейса\&. LPSTR cmdArgs - команда для fastboot вида 'fastboot X'\&. 
.PP
См\&. определение в файле ADB_mod\&.cpp строка 36
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
