.TH "ADB_slave.cpp" 3 "Сб 16 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADB_slave.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ADB_mod\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBadb_state\fP ()"
.br
.ti -1c
.RI "void \fBadb_flash\fP ()"
.br
.ti -1c
.RI "void \fBadb_root\fP ()"
.br
.in -1c
.SH "Функции"
.PP 
.SS "void adb_flash ()"
Вызов модуля установки кастомной рекавери\&. Требуется экстремальный пересмотр, ничего не работает\&. 
.PP
См\&. определение в файле ADB_slave\&.cpp строка 15
.SS "void adb_root ()"
Вызов модуля получения root-прав\&. Требуется тестирование на работоспособность\&. 
.PP
См\&. определение в файле ADB_slave\&.cpp строка 30
.SS "void adb_state ()"
Вызов модуля проверки состояния устройства\&. 
.PP
См\&. определение в файле ADB_slave\&.cpp строка 6
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
