.TH "CheckAgreement.h" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CheckAgreement.h \- Заголовочный файл с подключением модуля проверки согласия с лицензией\&.  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBi_checkagreement\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля проверки согласия с лицензией\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBCheckAgreement\&.h\fP
.SH "Функции"
.PP 
.SS "int i_checkagreement ()"
Вызов модуля проверки согласия пользователя с правилами\&. 
.PP
\fBВозвращает:\fP
.RS 4
0 - пользователь не согласен с условиями программы, выход из программы\&. 1 - пользователь согласен с условиями программы, запуск программы\&. 
.RE
.PP

.PP
См\&. определение в файле CheckAgreement\&.cpp строка 66
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
