.TH "CheckAgreement.cpp" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CheckAgreement.cpp \- Модуль проверки согласия пользователя с правилами\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <conio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include '\&.\&.\\core\\Color\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Logo\&.h'\fP
.br
\fC#include '\&.\&.\\core\\ConstantsMenu\&.h'\fP
.br
\fC#include '\&.\&.\\io\\RulesList\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_checkagreement_choice\fP (size_t choice)"
.br
.ti -1c
.RI "int \fBi_checkagreement\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Модуль проверки согласия пользователя с правилами\&. 


.PP
См\&. определение в файле \fBCheckAgreement\&.cpp\fP
.SH "Функции"
.PP 
.SS "int i_checkagreement ()"
Вызов модуля проверки согласия пользователя с правилами\&. 
.PP
\fBВозвращает:\fP
.RS 4
0 - пользователь не согласен с условиями программы, выход из программы\&. 1 - пользователь согласен с условиями программы, запуск программы\&. 
.RE
.PP

.PP
\fBПримеры: \fP
.in +1c
\fBcheckagreement\&.cpp\fP\&.
.PP
См\&. определение в файле CheckAgreement\&.cpp строка 66
.SS "void v_checkagreement_choice (size_t choice)"
Переключение пунктов меню 
.PP
\fBАргументы:\fP
.RS 4
\fIchoice\fP выбор 
.RE
.PP

.PP
См\&. определение в файле CheckAgreement\&.cpp строка 26
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
