.TH "Constants.h" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constants.h \- Заголовочный файл с константами\&.  

.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBradix\fP"
.br
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const size_t \fBradix::buff_size\fP = 32"
.br
.ti -1c
.RI "const size_t \fBradix::buff_ruleslist\fP = 256"
.br
.ti -1c
.RI "const char \fBradix::logger_list\fP [] = 'logger\&.log'"
.br
.ti -1c
.RI "const char \fBradix::settings_list\fP [] = 'settings\&.ini'"
.br
.ti -1c
.RI "const char \fBradix::rules_list\fP [] = 'rules\&.txt'"
.br
.ti -1c
.RI "const char \fBradix::firmware_way\fP [] = '\\\\assets\\\\firmware\\\\'"
.br
.ti -1c
.RI "const char \fBradix::patch\fP [] = '\\\\assets\\\\'"
.br
.ti -1c
.RI "const char \fBradix::expansion_file\fP [] = '\&.zip'"
.br
.ti -1c
.RI "const char \fBradix::recovery_file\fP [] = 'recovery\&.img'"
.br
.ti -1c
.RI "const char \fBradix::su_file\fP [] = 'su\&.zip'"
.br
.ti -1c
.RI "const char \fBradix::not_found\fP [] = ' not found\&.'"
.br
.ti -1c
.RI "const char \fBradix::found\fP [] = ' found\&.'"
.br
.ti -1c
.RI "const char \fBradix::ch_user_continue\fP [] = 'The user continued the program despite the error\&.'"
.br
.ti -1c
.RI "const char \fBradix::ch_user_not_continue\fP [] = 'The user did not continue the program despite the error\&.'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с константами\&. 


.PP
См\&. определение в файле \fBConstants\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
