.TH "ConstantsMenu.h" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstantsMenu.h \- Заголовочный файл с константами меню\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBmenu\fP"
.br
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const std::string \fBmenu::indentation\fP = ' '"
.br
.ti -1c
.RI "const std::string \fBmenu::frame_left\fP = ' <'"
.br
.ti -1c
.RI "const std::string \fBmenu::frame_right\fP = '> '"
.br
.ti -1c
.RI "const size_t \fBmenu::loading_size\fP = 25"
.br
.ti -1c
.RI "const bool \fBmenu::loading_check_module\fP = false"
.br
.ti -1c
.RI "const size_t \fBmenu::loading_check_module_sleep\fP = 1000"
.br
.ti -1c
.RI "const char \fBmenu::loading_left\fP = '['"
.br
.ti -1c
.RI "const char \fBmenu::loading_right\fP = ']'"
.br
.ti -1c
.RI "const char \fBmenu::loading_progress\fP = '|'"
.br
.ti -1c
.RI "const char \fBmenu::loading_indenting\fP = ' '"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с константами меню\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBConstantsMenu\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
