.TH "Constants.h" 3 "Чт 14 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constants.h \- Заголовочный файл с константами\&.  

.SH SYNOPSIS
.br
.PP
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBradix\fP"
.br
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const size_t \fBradix::buff_size\fP = 32"
.br
.ti -1c
.RI "const size_t \fBradix::length_url\fP = 64"
.br
.ti -1c
.RI "const size_t \fBradix::buff_ruleslist\fP = 256"
.br
.ti -1c
.RI "const char \fBradix::logger_list\fP [] = 'logger\&.log'"
.br
.ti -1c
.RI "const char \fBradix::settings_list\fP [] = 'settings\&.ini'"
.br
.ti -1c
.RI "const char \fBradix::address_list\fP [] = 'ip\&.ini'"
.br
.ti -1c
.RI "const char \fBradix::rules_list\fP [] = 'rules\&.txt'"
.br
.ti -1c
.RI "const char \fBradix::firmware_way\fP [] = '\\\\assets\\\\firmware\\\\'"
.br
.ti -1c
.RI "const char \fBradix::patch\fP [] = '\\\\assets\\\\'"
.br
.ti -1c
.RI "const char \fBradix::expansion_file\fP [] = '\&.zip'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с константами\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBConstants\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
