.TH "Содержание директории core" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории core
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBADB_mod\&.cpp\fP"
.br
.RI "Модуль работы с adb\&. "
.ti -1c
.RI "файл \fBADB_mod\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля работы с adb\&. "
.ti -1c
.RI "файл \fBADB_slave\&.cpp\fP"
.br
.RI "Модуль работы с adb\&. "
.ti -1c
.RI "файл \fBADB_slave\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля работы с adb\&. "
.ti -1c
.RI "файл \fBCheckingFiles\&.cpp\fP"
.br
.RI "Модуль проверки файлов для рутирования телефона\&. "
.ti -1c
.RI "файл \fBCheckingFiles\&.h\fP"
.br
.RI "Заголовочный файл с вызовом модуля проверки файлов для рутирования телефона\&. "
.ti -1c
.RI "файл \fBColor\&.cpp\fP"
.br
.RI "Модуль работы с цветом в консоли\&. "
.ti -1c
.RI "файл \fBColor\&.h\fP"
.br
.RI "Заголовочный файл с цветами и модулем смены цвета в консоли\&. "
.ti -1c
.RI "файл \fBConstants\&.h\fP"
.br
.RI "Заголовочный файл с константами\&. "
.ti -1c
.RI "файл \fBConstantsMenu\&.h\fP"
.br
.RI "Заголовочный файл с константами меню\&. "
.ti -1c
.RI "файл \fBInitialization\&.cpp\fP"
.br
.RI "Модуль проверки стандартных файлов программы\&. "
.ti -1c
.RI "файл \fBInitialization\&.h\fP"
.br
.RI "Заголовочный файл с вызовом модуля инициализации "
.ti -1c
.RI "файл \fBLogo\&.h\fP"
.br
.RI "Заголовочный файл с логотипами\&. "
.ti -1c
.RI "файл \fBMain\&.cpp\fP"
.br
.RI "Главный файл программы "
.ti -1c
.RI "файл \fBRadix\&.cpp\fP"
.br
.RI "Главный файл программы "
.ti -1c
.RI "файл \fBRadix\&.h\fP"
.br
.RI "Заголовочный файл с вызовом главной функции программы "
.in -1c
