.TH "Содержание директории ui" 3 "Чт 14 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории ui
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBCheckAgreement\&.cpp\fP"
.br
.RI "Модуль проверки согласия пользователя с правилами\&. "
.ti -1c
.RI "файл \fBCheckAgreement\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля проверки согласия с лицензией\&. "
.ti -1c
.RI "файл \fBExit\&.cpp\fP"
.br
.RI "Модуль выхода из программы\&. "
.ti -1c
.RI "файл \fBExit\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля выхода из программы\&. "
.ti -1c
.RI "файл \fBLoadScale\&.cpp\fP"
.br
.RI "Модуль вывода шкалы загрузки\&. "
.ti -1c
.RI "файл \fBLoadScale\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля вывода шкалы загрузки\&. "
.ti -1c
.RI "файл \fBMainMenu\&.cpp\fP"
.br
.RI "Модуль вывода главного меню программы\&. "
.ti -1c
.RI "файл \fBMainMenu\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля главного меню\&. "
.in -1c
