.TH "Содержание директории core" 3 "Пн 25 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории core
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBADB_mod\&.cpp\fP"
.br
.RI "Модуль работы с adb\&. "
.ti -1c
.RI "файл \fBADB_mod\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля работы с adb\&. "
.ti -1c
.RI "файл \fBColor\&.cpp\fP"
.br
.RI "Модуль работы с цветом в консоли\&. "
.ti -1c
.RI "файл \fBColor\&.h\fP"
.br
.RI "Заголовочный файл с цветами и модулем смены цвета в консоли\&. "
.ti -1c
.RI "файл \fBConstants\&.h\fP"
.br
.RI "Заголовочный файл с константами\&. "
.ti -1c
.RI "файл \fBMain\&.cpp\fP"
.br
.RI "Главный файл программы "
.ti -1c
.RI "файл \fBOperations\&.cpp\fP"
.br
.RI "Модуль проверки стандартных файлов программы и вызова алгоритма рутирования\&. "
.ti -1c
.RI "файл \fBOperations\&.h\fP"
.br
.RI "Заголовочный файл с вызовом модуля проверки стандартных файлов программы и вызова алгоритма рутирования\&. "
.in -1c
