.TH "Содержание директории io" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории io
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBLogger\&.cpp\fP"
.br
.RI "Модуль логирования "
.ti -1c
.RI "файл \fBLogger\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля логирования\&. "
.ti -1c
.RI "файл \fBRulesList\&.cpp\fP"
.br
.RI "Модуль чтения правил\&. "
.ti -1c
.RI "файл \fBRulesList\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля чтения правил\&. "
.ti -1c
.RI "файл \fBSettings\&.cpp\fP"
.br
.RI "Модуль настроек\&. Парсит переменные в файлах "
.ti -1c
.RI "файл \fBSettings\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля настроек\&. "
.ti -1c
.RI "файл \fBTemplates\&.cpp\fP"
.br
.RI "Функции для создания стандартных файлов программы\&. "
.ti -1c
.RI "файл \fBTemplates\&.h\fP"
.br
.RI "Заголовочный файл с подключением модуля создания стандартных файлов программы\&. "
.in -1c
