.TH "Exit.h" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exit.h \- Заголовочный файл с подключением модуля выхода из программы\&.  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_exit\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля выхода из программы\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBExit\&.h\fP
.SH "Функции"
.PP 
.SS "void v_exit ()"
Вывод текста\&. Выход из программы\&. 
.PP
См\&. определение в файле Exit\&.cpp строка 16
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
