.TH "Exit.cpp" 3 "Сб 16 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exit.cpp \- Модуль выхода из программы\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '\&.\&.\\core\\Color\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Logo\&.h'\fP
.br
\fC#include '\&.\&.\\core\\ConstantsMenu\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_exit\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Модуль выхода из программы\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBExit\&.cpp\fP
.SH "Функции"
.PP 
.SS "void v_exit ()"
Вывод текста\&. Выход из программы\&. 
.PP
См\&. определение в файле Exit\&.cpp строка 15
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
