.TH "Initialization.h" 3 "Сб 16 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Initialization.h \- Заголовочный файл с вызовом модуля инициализации  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_initialization\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с вызовом модуля инициализации 

Вызов: 
.PP
.nf
void v_initialization();

.fi
.PP
.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBInitialization\&.h\fP
.SH "Функции"
.PP 
.SS "void v_initialization ()"
Главная функция программы
.PP
Проверяет наличие 3 стандартных файлов программы 
.PP
.nf
logger.log

rules.txt

settings.ini
.fi
.PP
 
.PP
См\&. определение в файле Initialization\&.cpp строка 46
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
