.TH "Items.h" 3 "Пн 25 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Items.h \- Заголовочный файл с подключением меню\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "std::string \fBs_mainmenu\fP ()"
.br
.ti -1c
.RI "std::string \fBs_querymenu\fP (std::string item)"
.br
.ti -1c
.RI "std::string \fBs_checkagreement\fP ()"
.br
.ti -1c
.RI "void \fBv_manual\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением меню\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBItems\&.h\fP
.SH "Функции"
.PP 
.SS "std::string s_checkagreement ()"
Проверка согласия пользователя с пользовательским соглашением\&. 
.PP
\fBВозвращает:\fP
.RS 4
Выбранный пункт меню\&. 
.RE
.PP

.PP
См\&. определение в файле Items\&.cpp строка 87
.SS "std::string s_mainmenu ()"
Главное меню\&. 
.PP
\fBВозвращает:\fP
.RS 4
Выбранный пункт меню\&. 
.RE
.PP

.PP
См\&. определение в файле Items\&.cpp строка 27
.SS "std::string s_querymenu (std::string item)"
Сообщение с вопросом для пользователя\&. 
.PP
\fBАргументы:\fP
.RS 4
\fIitem\fP Строка до выполнения модуля меню\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Выбранный пункт меню\&. 
.RE
.PP

.SS "void v_manual ()"
Инструкция к программе\&. 
.PP
См\&. определение в файле Items\&.cpp строка 113
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
