.TH "LoadScale.h" 3 "Сб 16 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadScale.h \- Заголовочный файл с подключением модуля вывода шкалы загрузки\&.  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_loadscale\fP (size_t position)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля вывода шкалы загрузки\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBLoadScale\&.h\fP
.SH "Функции"
.PP 
.SS "void v_loadscale (size_t position)"
Переключение пунктов меню 
.PP
\fBАргументы:\fP
.RS 4
\fIposition\fP значение до которого отрисовывать шкалу\&. 
.RE
.PP

.PP
См\&. определение в файле LoadScale\&.cpp строка 18
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
