.TH "Logo.h" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logo.h \- Заголовочный файл с логотипами\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBlogo\fP"
.br
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "const std::string \fBlogo::border\fP = '===========================\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::little_help\fP = '==== <\- use to move \-> ====\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::license\fP = 'Do you agree with the license?\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::move_indentation\fP = ' '"
.br
.ti -1c
.RI "const std::string \fBlogo::move\fP = '<\- use to move \->\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::radix\fP = ' _____ _ _ \\n | __ \\\\ | (_) \\n | |__) |__ _ __| |___ __\\n | _ // _` |/ _` | \\\\ \\\\/ /\\n | | \\\\ \\\\ (_| | (_| | |> < \\n |_| \\\\_\\\\__,_|\\\\__,_|_/_/\\\\_\\\\ \\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::loading\fP = ' _ _ \\n | | | |\\n | | ___ __ _ __| |\\n | | / _ \\\\ / _` |/ _` |\\n | |___| (_) | (_| | (_| |\\n |______\\\\___/ \\\\__,_|\\\\__,_|\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::exit\fP = ' ______ _ _ \\n | ____| (_) | \\n | |__ __ ___| |_ \\n | __| \\\\ \\\\/ / | __|\\n | |____ > <| | |_ \\n |______/_/\\\\_\\\\_|\\\\__|\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::s_continue\fP = 'Continue?\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::s_manual\fP = ' Manual\\n1) Put the file recovery\&.img in the \fBroot\fP of the program\&.\\n2) Put the file su\&.zip in the \fBroot\fP of the program\&.\\n3) Continue\&.\\n'"
.br
.ti -1c
.RI "const std::string \fBlogo::enter\fP = 'Press any key to continue\&.'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с логотипами\&. 


.PP
См\&. определение в файле \fBLogo\&.h\fP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
