.TH "Main.cpp" 3 "Чт 21 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main.cpp \- Главный файл программы  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include '\&.\&.\\core\\Operations\&.h'\fP
.br
\fC#include '\&.\&.\\io\\Logger\&.h'\fP
.br
\fC#include '\&.\&.\\ui\\Menu\&.h'\fP
.br
\fC#include '\&.\&.\\ui\\Items\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Главный файл программы 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBMain\&.cpp\fP
.SH "Функции"
.PP 
.SS "int main ()"

.PP
\fBВозвращает:\fP
.RS 4
Код завершения программы Вызов программы компилятором 
.RE
.PP

.PP
\fBПримеры: \fP
.in +1c
\fBcolor\&.cpp\fP, \fBconstants\&.cpp\fP, \fBitems\&.cpp\fP, \fBlog\&.cpp\fP, \fBmenu\&.cpp\fP, \fBOperations\&.cpp\fP, \fBOperations_Initialization\&.cpp\fP, \fBsettings\&.cpp\fP и \fBtemplates\&.cpp\fP\&.
.PP
См\&. определение в файле Main\&.cpp строка 19
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
