.TH "Manual.h" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Manual.h \- Заголовочный файл с подключением модуля инструкции\&.  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_manual\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля инструкции\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBManual\&.h\fP
.SH "Функции"
.PP 
.SS "void v_manual ()"
Вызов модуля инструкции\&. Вывод инструкции в консоль\&. 
.PP
См\&. определение в файле Manual\&.cpp строка 22
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
