.TH "Menu.h" 3 "Пн 25 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.h \- Заголовочный файл с подключением модуля создания меню\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBmenu_s\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "std::string \fBs_menu\fP (\fBmenu_s\fP menu)"
.br
.ti -1c
.RI "void \fBpause\fP ()"
.br
.ti -1c
.RI "void \fBv_exit\fP ()"
.br
.ti -1c
.RI "void \fBv_loadscale\fP (size_t position)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля создания меню\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBMenu\&.h\fP
.SH "Функции"
.PP 
.SS "void pause ()"
Паузка до нажатия любой клавиши\&. 
.PP
См\&. определение в файле Menu\&.cpp строка 107
.SS "std::string s_menu (\fBmenu_s\fP menu)"
Модуль создания меню\&. 
.PP
\fBАргументы:\fP
.RS 4
\fImenu\fP Список с параметрами создаваемого меню\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Выбранный пункт меню\&. 
.RE
.PP

.PP
См\&. определение в файле Menu\&.cpp строка 61
.SS "void v_exit ()"
Выход из программы\&. Вывод текста\&. 
.PP
См\&. определение в файле Menu\&.cpp строка 114
.SS "void v_loadscale (size_t position)"
Шкала загрузки\&. 
.PP
\fBАргументы:\fP
.RS 4
\fIposition\fP значение до которого отрисовывать шкалу\&.
.RE
.PP
Шкала загрузки 
.PP
\fBАргументы:\fP
.RS 4
\fIposition\fP значение до которого отрисовывать шкалу\&. 
.RE
.PP

.PP
См\&. определение в файле Menu\&.cpp строка 128
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
