.TH "Menu.cpp" 3 "Чт 21 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.cpp \- Модуль создания меню\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <conio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <Windows\&.h>\fP
.br
\fC#include '\&.\&.\\core\\Constants\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Color\&.h'\fP
.br
\fC#include '\&.\&.\\ui\\Menu\&.h'\fP
.br
\fC#include '\&.\&.\\io\\Logger\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "string \fBs_menu_choice\fP (size_t choice, \fBmenu_s\fP menu)"
.br
.ti -1c
.RI "string \fBs_menu\fP (\fBmenu_s\fP menu)"
.br
.ti -1c
.RI "void \fBpause\fP ()"
.br
.ti -1c
.RI "void \fBv_exit\fP ()"
.br
.ti -1c
.RI "void \fBv_loadscale\fP (size_t position)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Модуль создания меню\&. 


.PP
См\&. определение в файле \fBMenu\&.cpp\fP
.SH "Функции"
.PP 
.SS "void pause ()"
Паузка до нажатия любой клавиши\&. 
.PP
См\&. определение в файле Menu\&.cpp строка 99
.SS "string s_menu (\fBmenu_s\fP menu)"
Модуль создания меню\&. 
.PP
\fBАргументы:\fP
.RS 4
\fImenu\fP Список с параметрами создаваемого меню\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Выбранный пункт меню\&. 
.RE
.PP

.PP
\fBПримеры: \fP
.in +1c
\fBmenu\&.cpp\fP\&.
.PP
См\&. определение в файле Menu\&.cpp строка 57
.SS "string s_menu_choice (size_t choice, \fBmenu_s\fP menu)"
Отрисовка модуля создания меню\&. 
.PP
\fBАргументы:\fP
.RS 4
\fIchoice\fP Выбранный пункт меню\&. 
.br
\fImenu\fP Список с параметрами создаваемого меню\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Выбранный пункт меню\&. 
.RE
.PP

.PP
См\&. определение в файле Menu\&.cpp строка 31
.SS "void v_exit ()"
Выход из программы\&. Вывод текста\&. 
.PP
См\&. определение в файле Menu\&.cpp строка 106
.SS "void v_loadscale (size_t position)"
Шкала загрузки 
.PP
\fBАргументы:\fP
.RS 4
\fIposition\fP значение до которого отрисовывать шкалу\&. 
.RE
.PP

.PP
См\&. определение в файле Menu\&.cpp строка 127
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
