.TH "menu" 3 "Чт 14 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu
.SH SYNOPSIS
.br
.PP
.SS "Переменные"

.in +1c
.ti -1c
.RI "const std::string \fBindentation\fP = ' '"
.br
.ti -1c
.RI "const std::string \fBframe_left\fP = ' <'"
.br
.ti -1c
.RI "const std::string \fBframe_right\fP = '> '"
.br
.ti -1c
.RI "const size_t \fBloading_size\fP = 25"
.br
.ti -1c
.RI "const bool \fBloading_check_module\fP = false"
.br
.ti -1c
.RI "const size_t \fBloading_check_module_sleep\fP = 1000"
.br
.ti -1c
.RI "const char \fBloading_left\fP = '['"
.br
.ti -1c
.RI "const char \fBloading_right\fP = ']'"
.br
.ti -1c
.RI "const char \fBloading_progress\fP = '|'"
.br
.ti -1c
.RI "const char \fBloading_indenting\fP = ' '"
.br
.in -1c
.SH "Переменные"
.PP 
.SS "const std::string menu::frame_left = ' <'"
Левая скобка и отступ слева\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 14
.SS "const std::string menu::frame_right = '> '"
Правая скобка и отступ справа\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 16
.SS "const std::string menu::indentation = ' '"
Отступ между пунктами меню\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 12
.SS "const bool menu::loading_check_module = false"
Включение задержки, для проверки работоспособности модуля загрузки\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 21
.SS "const size_t menu::loading_check_module_sleep = 1000"
Пауза в мс для проверки работоспособности модуля загрузки \&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 23
.SS "const char menu::loading_indenting = ' '"
Модуль загрузки\&. Значение после шкалы прогресса\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 37
.SS "const char menu::loading_left = '['"
Модуль загрузки\&. Левая скобка\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 31
.SS "const char menu::loading_progress = '|'"
Модуль загрузки\&. Шкала прогресса\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 35
.SS "const char menu::loading_right = ']'"
Модуль загрузки\&. Правая скобка\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 33
.SS "const size_t menu::loading_size = 25"
Размер шкалы модуля загрузки\&. 
.PP
См\&. определение в файле ConstantsMenu\&.h строка 19
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
