.TH "menu" 3 "Пн 25 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu
.SH SYNOPSIS
.br
.PP
.SS "Переменные"

.in +1c
.ti -1c
.RI "const std::string \fBindentation\fP = ' '"
.br
.ti -1c
.RI "const std::string \fBframe_left\fP = ' <'"
.br
.ti -1c
.RI "const std::string \fBframe_right\fP = '> '"
.br
.ti -1c
.RI "const size_t \fBloading_size\fP = 25"
.br
.ti -1c
.RI "const bool \fBloading_check_module\fP = false"
.br
.ti -1c
.RI "const size_t \fBloading_check_module_sleep\fP = 1000"
.br
.ti -1c
.RI "const char \fBloading_left\fP = '['"
.br
.ti -1c
.RI "const char \fBloading_right\fP = ']'"
.br
.ti -1c
.RI "const char \fBloading_progress\fP = '|'"
.br
.ti -1c
.RI "const char \fBloading_indenting\fP = ' '"
.br
.ti -1c
.RI "const size_t \fBbackspace\fP = 8"
.br
.ti -1c
.RI "const size_t \fBenter\fP = 13"
.br
.ti -1c
.RI "const size_t \fBesc\fP = 27"
.br
.ti -1c
.RI "const size_t \fBspace\fP = 32"
.br
.ti -1c
.RI "const size_t \fBarrow_up\fP = 72"
.br
.ti -1c
.RI "const size_t \fBarrow_left\fP = 75"
.br
.ti -1c
.RI "const size_t \fBarrow_right\fP = 77"
.br
.ti -1c
.RI "const size_t \fBarrow_down\fP = 80"
.br
.ti -1c
.RI "const size_t \fBspecial\fP = 224"
.br
.in -1c
.SH "Переменные"
.PP 
.SS "const size_t menu::arrow_down = 80"
Arrow down key\&. 
.PP
См\&. определение в файле Constants\&.h строка 112
.SS "const size_t menu::arrow_left = 75"
Arrow left key\&. 
.PP
См\&. определение в файле Constants\&.h строка 106
.SS "const size_t menu::arrow_right = 77"
Arrow right key\&. 
.PP
См\&. определение в файле Constants\&.h строка 109
.SS "const size_t menu::arrow_up = 72"
Arrow up key\&. 
.PP
См\&. определение в файле Constants\&.h строка 103
.SS "const size_t menu::backspace = 8"
Backspace key\&. 
.PP
См\&. определение в файле Constants\&.h строка 91
.SS "const size_t menu::enter = 13"
Enter key\&. 
.PP
См\&. определение в файле Constants\&.h строка 94
.SS "const size_t menu::esc = 27"
ESC key\&. 
.PP
См\&. определение в файле Constants\&.h строка 97
.SS "const std::string menu::frame_left = ' <'"
Левая скобка и отступ слева\&. 
.PP
См\&. определение в файле Constants\&.h строка 64
.SS "const std::string menu::frame_right = '> '"
Правая скобка и отступ справа\&. 
.PP
См\&. определение в файле Constants\&.h строка 67
.SS "const std::string menu::indentation = ' '"
Отступ между пунктами меню\&. 
.PP
См\&. определение в файле Constants\&.h строка 61
.SS "const bool menu::loading_check_module = false"
Включение задержки, для проверки работоспособности модуля загрузки\&. 
.PP
См\&. определение в файле Constants\&.h строка 73
.SS "const size_t menu::loading_check_module_sleep = 1000"
Пауза в мс для проверки работоспособности модуля загрузки \&. 
.PP
См\&. определение в файле Constants\&.h строка 76
.SS "const char menu::loading_indenting = ' '"
Модуль загрузки\&. Значение после шкалы прогресса\&. 
.PP
См\&. определение в файле Constants\&.h строка 88
.SS "const char menu::loading_left = '['"
Модуль загрузки\&. Левая скобка\&. 
.PP
См\&. определение в файле Constants\&.h строка 79
.SS "const char menu::loading_progress = '|'"
Модуль загрузки\&. Шкала прогресса\&. 
.PP
См\&. определение в файле Constants\&.h строка 85
.SS "const char menu::loading_right = ']'"
Модуль загрузки\&. Правая скобка\&. 
.PP
См\&. определение в файле Constants\&.h строка 82
.SS "const size_t menu::loading_size = 25"
Размер шкалы модуля загрузки\&. 
.PP
См\&. определение в файле Constants\&.h строка 70
.SS "const size_t menu::space = 32"
Space key\&. 
.PP
См\&. определение в файле Constants\&.h строка 100
.SS "const size_t menu::special = 224"
Special key\&. 
.PP
См\&. определение в файле Constants\&.h строка 115
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
