.TH "radix" 3 "Сб 16 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radix
.SH SYNOPSIS
.br
.PP
.SS "Переменные"

.in +1c
.ti -1c
.RI "const size_t \fBbuff_size\fP = 32"
.br
.ti -1c
.RI "const size_t \fBlength_url\fP = 64"
.br
.ti -1c
.RI "const size_t \fBbuff_ruleslist\fP = 256"
.br
.ti -1c
.RI "const char \fBlogger_list\fP [] = 'logger\&.log'"
.br
.ti -1c
.RI "const char \fBsettings_list\fP [] = 'settings\&.ini'"
.br
.ti -1c
.RI "const char \fBaddress_list\fP [] = 'ip\&.ini'"
.br
.ti -1c
.RI "const char \fBrules_list\fP [] = 'rules\&.txt'"
.br
.ti -1c
.RI "const char \fBfirmware_way\fP [] = '\\\\assets\\\\firmware\\\\'"
.br
.ti -1c
.RI "const char \fBpatch\fP [] = '\\\\assets\\\\'"
.br
.ti -1c
.RI "const char \fBexpansion_file\fP [] = '\&.zip'"
.br
.in -1c
.SH "Переменные"
.PP 
.SS "const char radix::address_list[] = 'ip\&.ini'"
Файл с адресами\&. 
.PP
См\&. определение в файле Constants\&.h строка 31
.SS "const size_t radix::buff_ruleslist = 256"
Размер буфера для чтения правил программы\&. В основном используется для чтения правил программы\&. 
.PP
См\&. определение в файле Constants\&.h строка 24
.SS "const size_t radix::buff_size = 32"
Размер буфера\&. В основном используется для чтения строк из файла\&. 
.PP
См\&. определение в файле Constants\&.h строка 14
.SS "const char radix::expansion_file[] = '\&.zip'"
Расширение прошивок \&. 
.PP
См\&. определение в файле Constants\&.h строка 41
.SS "const char radix::firmware_way[] = '\\\\assets\\\\firmware\\\\'"
Путь к прошивкам\&. 
.PP
См\&. определение в файле Constants\&.h строка 36
.SS "const size_t radix::length_url = 64"
Размер буфера под ссылку\&. В основном используется для чтения адресов из файла\&. 
.PP
См\&. определение в файле Constants\&.h строка 19
.SS "const char radix::logger_list[] = 'logger\&.log'"
Файл с выводом логера\&. 
.PP
См\&. определение в файле Constants\&.h строка 27
.SS "const char radix::patch[] = '\\\\assets\\\\'"
Путь к дополнительным файлам программы\&. 
.PP
См\&. определение в файле Constants\&.h строка 38
.SS "const char radix::rules_list[] = 'rules\&.txt'"
Файл с пользовательским соглашением\&. 
.PP
См\&. определение в файле Constants\&.h строка 33
.SS "const char radix::settings_list[] = 'settings\&.ini'"
Файл с настройками программы\&. 
.PP
См\&. определение в файле Constants\&.h строка 29
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
