.TH "Radix.h" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Radix.h \- Заголовочный файл с вызовом главной функции программы  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBRadix\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с вызовом главной функции программы 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBRadix\&.h\fP
.SH "Функции"
.PP 
.SS "void Radix ()"
Запуск программы 
.PP
См\&. определение в файле Radix\&.cpp строка 16
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
