.TH "Radix.cpp" 3 "Пн 18 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Radix.cpp \- Главный файл программы  

.SH SYNOPSIS
.br
.PP
\fC#include 'Initialization\&.h'\fP
.br
\fC#include '\&.\&.\\ui\\MainMenu\&.h'\fP
.br
\fC#include '\&.\&.\\ui\\CheckAgreement\&.h'\fP
.br
\fC#include '\&.\&.\\ui\\Manual\&.h'\fP
.br
\fC#include '\&.\&.\\ui\\Exit\&.h'\fP
.br
\fC#include '\&.\&.\\io\\Logger\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBRadix\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Главный файл программы 


.PP
См\&. определение в файле \fBRadix\&.cpp\fP
.SH "Функции"
.PP 
.SS "void Radix ()"
Запуск программы 
.PP
\fBПримеры: \fP
.in +1c
\fBradix\&.cpp\fP\&.
.PP
См\&. определение в файле Radix\&.cpp строка 16
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
