.TH "Settings.h" 3 "Пн 25 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Settings.h \- Заголовочный файл с подключением модуля настроек\&.  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "bool \fBb_settings\fP (char ch_arr_value[])"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля настроек\&. 


.PP
См\&. определение в файле \fBSettings\&.h\fP
.SH "Функции"
.PP 
.SS "bool b_settings (char ch_arr_value[])"
Парсинг параметров\&. 
.PP
\fBАргументы:\fP
.RS 4
\fIch_arr_value[]\fP Значение, которое надо найти в файле\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Значение переменной true false
.RE
.PP
Парсинг параметров 
.PP
\fBАргументы:\fP
.RS 4
\fIch_arr_value[]\fP Значение, которое надо найти в файле\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
Значение переменной true false 
.RE
.PP

.PP
См\&. определение в файле Settings\&.cpp строка 22
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
