.TH "Templates.cpp" 3 "Чт 14 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Templates.cpp \- Функции для создания стандартных файлов программы\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include 'Templates\&.h'\fP
.br
\fC#include '\&.\&.\\core\\Constants\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_templates_create_logger_log\fP ()"
.br
.ti -1c
.RI "void \fBv_templates_create_rules_txt\fP ()"
.br
.ti -1c
.RI "void \fBv_templates_create_settings_ini\fP ()"
.br
.ti -1c
.RI "void \fBv_templates_create_ip_ini\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Функции для создания стандартных файлов программы\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBTemplates\&.cpp\fP
.SH "Функции"
.PP 
.SS "void v_templates_create_ip_ini ()"
Создание файла ip\&. 
.PP
.nf
ip.ini - файл с ip адресами
.fi
.PP
 
.PP
См\&. определение в файле Templates\&.cpp строка 83
.SS "void v_templates_create_logger_log ()"
Создание файла пользовательского соглашения\&. 
.PP
.nf
logger.log - файл с логом вывода
.fi
.PP
 
.PP
См\&. определение в файле Templates\&.cpp строка 21
.SS "void v_templates_create_rules_txt ()"
Создание файла пользовательского соглашения\&. 
.PP
.nf
rules.txt - файл с пользовательским соглашением
.fi
.PP
 
.PP
См\&. определение в файле Templates\&.cpp строка 38
.SS "void v_templates_create_settings_ini ()"
Создание файла настроек\&. 
.PP
.nf
settings.ini - файл с настройками
.fi
.PP
 
.PP
См\&. определение в файле Templates\&.cpp строка 59
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
