.TH "Templates.h" 3 "Пн 25 Дек 2017" "Radix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Templates.h \- Заголовочный файл с подключением модуля создания стандартных файлов программы\&.  

.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBv_templates_create_logger_log\fP ()"
.br
.ti -1c
.RI "void \fBv_templates_create_settings_ini\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Заголовочный файл с подключением модуля создания стандартных файлов программы\&. 


.PP
\fBАвтор:\fP
.RS 4
SavaLione 
.RE
.PP

.PP
См\&. определение в файле \fBTemplates\&.h\fP
.SH "Функции"
.PP 
.SS "void v_templates_create_logger_log ()"
Создание файла пользовательского соглашения\&. 
.PP
.nf
logger.log - файл с логом вывода.
.fi
.PP
.PP
Создание файла пользовательского соглашения\&. 
.PP
.nf
logger.log - файл с логом вывода
.fi
.PP
 
.PP
См\&. определение в файле Templates\&.cpp строка 24
.SS "void v_templates_create_settings_ini ()"
Создание файла настроек\&. 
.PP
.nf
settings.ini - файл с настройками.
.fi
.PP
.PP
Создание файла настроек\&. 
.PP
.nf
settings.ini - файл с настройками
.fi
.PP
 
.PP
См\&. определение в файле Templates\&.cpp строка 41
.SH "Автор"
.PP 
Автоматически создано Doxygen для Radix из исходного текста\&.
