var menudata={children:[
{text:"Титульная страница",url:"index.html"},
{text:"Пространства имен",url:"namespaces.html",children:[
{text:"Пространства имен",url:"namespaces.html"},
{text:"Члены пространств имен",url:"namespacemembers.html",children:[
{text:"Указатель",url:"namespacemembers.html",children:[
{text:"a",url:"namespacemembers.html#index_a"},
{text:"b",url:"namespacemembers.html#index_b"},
{text:"c",url:"namespacemembers.html#index_c"},
{text:"e",url:"namespacemembers.html#index_e"},
{text:"f",url:"namespacemembers.html#index_f"},
{text:"i",url:"namespacemembers.html#index_i"},
{text:"l",url:"namespacemembers.html#index_l"},
{text:"m",url:"namespacemembers.html#index_m"},
{text:"n",url:"namespacemembers.html#index_n"},
{text:"p",url:"namespacemembers.html#index_p"},
{text:"r",url:"namespacemembers.html#index_r"},
{text:"s",url:"namespacemembers.html#index_s"}]},
{text:"Переменные",url:"namespacemembers_vars.html",children:[
{text:"a",url:"namespacemembers_vars.html#index_a"},
{text:"b",url:"namespacemembers_vars.html#index_b"},
{text:"c",url:"namespacemembers_vars.html#index_c"},
{text:"e",url:"namespacemembers_vars.html#index_e"},
{text:"f",url:"namespacemembers_vars.html#index_f"},
{text:"i",url:"namespacemembers_vars.html#index_i"},
{text:"l",url:"namespacemembers_vars.html#index_l"},
{text:"m",url:"namespacemembers_vars.html#index_m"},
{text:"n",url:"namespacemembers_vars.html#index_n"},
{text:"p",url:"namespacemembers_vars.html#index_p"},
{text:"r",url:"namespacemembers_vars.html#index_r"},
{text:"s",url:"namespacemembers_vars.html#index_s"}]}]}]},
{text:"Классы",url:"annotated.html",children:[
{text:"Классы",url:"annotated.html"},
{text:"Алфавитный указатель классов",url:"classes.html"},
{text:"Члены классов",url:"functions.html",children:[
{text:"Указатель",url:"functions.html"},
{text:"Переменные",url:"functions_vars.html"}]}]},
{text:"Файлы",url:"files.html",children:[
{text:"Файлы",url:"files.html"},
{text:"Список членов всех файлов",url:"globals.html",children:[
{text:"Указатель",url:"globals.html",children:[
{text:"a",url:"globals.html#index_a"},
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"f",url:"globals.html#index_f"},
{text:"g",url:"globals.html#index_g"},
{text:"i",url:"globals.html#index_i"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"v",url:"globals.html#index_v"},
{text:"w",url:"globals.html#index_w"}]},
{text:"Функции",url:"globals_func.html",children:[
{text:"a",url:"globals_func.html#index_a"},
{text:"b",url:"globals_func.html#index_b"},
{text:"f",url:"globals_func.html#index_f"},
{text:"i",url:"globals_func.html#index_i"},
{text:"l",url:"globals_func.html#index_l"},
{text:"m",url:"globals_func.html#index_m"},
{text:"p",url:"globals_func.html#index_p"},
{text:"r",url:"globals_func.html#index_r"},
{text:"s",url:"globals_func.html#index_s"},
{text:"v",url:"globals_func.html#index_v"}]},
{text:"Перечисления",url:"globals_enum.html"},
{text:"Элементы перечислений",url:"globals_eval.html"}]}]},
{text:"Примеры",url:"examples.html"}]}
